// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmnfgwlrxijecorsehyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtbmZnd2xyeGlqZWNvcnNlaHl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzgyNzYsImV4cCI6MjA2NzU1NDI3Nn0.sHfOaiNSEAOIJl2LBIT5c7D6wjTuNkIp5gCmU8JET1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});